// Centralized Source of Truth for all Topic IDs.
// DO NOT manually edit strings in migrations or components.
// Import these constants instead.

export const TOPIC_IDS = {
  // MATHEMATICS
  MATH_S1_NUMBER_SYSTEMS: "m1-1",
  MATH_S1_BASIC_ALGEBRA: "m1-2",
  MATH_S1_GEOMETRY_BASICS: "m1-3",
  MATH_S1_FRACTIONS_DECIMALS_PERCENTAGES: "m1-4",
  MATH_S1_RATIO_AND_PROPORTION: "m1-5",
  MATH_S1_AREA_AND_PERIMETER: "m1-6",
  MATH_S1_INDICES_AND_POWERS: "m1-7",

  MATH_S2_PYTHAGORAS_THEOREM: "m2-1",
  MATH_S2_TRIGONOMETRY_BASICS: "m2-2",
  MATH_S2_SIMULTANEOUS_EQUATIONS: "m2-3",
  MATH_S2_ALGEBRAIC_FRACTIONS: "m2-4",
  MATH_S2_LINEAR_GRAPHS: "m2-5",
  MATH_S2_INEQUALITIES: "m2-6",
  MATH_S2_SETS_AND_VENN_DIAGRAMS: "m2-7",
  MATH_S2_TRANSFORMATION_GEOMETRY: "m2-8",

  MATH_S3_QUADRATIC_EQUATIONS: "m3-1",
  MATH_S3_CIRCLE_THEOREMS: "m3-2",
  MATH_S3_SEQUENCES_AND_SERIES: "m3-3",
  MATH_S3_TRIGONOMETRIC_IDENTITIES: "m3-4",
  MATH_S3_VARIATION: "m3-5",
  MATH_S3_LOGARITHMS: "m3-6",

  MATH_S4_MATRICES_AND_TRANSFORMATIONS: "m4-1",
  MATH_S4_STATISTICS_AND_PROBABILITY: "m4-2",
  MATH_S4_VECTORS: "m4-3",
  MATH_S4_CALCULUS_DIFFERENTIATION: "m4-4",
  MATH_S4_CALCULUS_INTEGRATION: "m4-5",
  MATH_S4_LINEAR_PROGRAMMING: "m4-6",

  // PHYSICS
  PHYSICS_S1_MEASUREMENT: "p1-1",
  PHYSICS_S1_STATES_OF_MATTER: "p1-2",
  PHYSICS_S1_FORCES_AND_THEIR_EFFECTS: "p1-3",
  PHYSICS_S1_ENERGY: "p1-4",

  PHYSICS_S2_FORCES_AND_MOTION: "p2-1",
  PHYSICS_S2_TURNING_EFFECTS_OF_FORCES: "p2-2",
  PHYSICS_S2_PRESSURE: "p2-3",
  PHYSICS_S2_WORK_ENERGY_AND_POWER: "p2-4",

  PHYSICS_S3_ELECTRICITY: "p3-1",
  PHYSICS_S3_MAGNETISM_AND_ELECTROMAGNETISM: "p3-2",
  PHYSICS_S3_THERMAL_PHYSICS: "p3-3",
  PHYSICS_S3_LIGHT: "p3-4",

  PHYSICS_S4_WAVES_AND_SOUND: "p4-1",
  PHYSICS_S4_ELECTROMAGNETIC_SPECTRUM: "p4-2",
  PHYSICS_S4_ATOMIC_AND_NUCLEAR_PHYSICS: "p4-3",
  PHYSICS_S4_ELECTRONICS: "p4-4",

  // CHEMISTRY
  CHEMISTRY_S1_INTRODUCTION: "c1-1",
  CHEMISTRY_S1_ACIDS_BASES_AND_INDICATORS: "c1-2",
  CHEMISTRY_S1_WATER_AND_HYDROGEN: "c1-3",
  CHEMISTRY_S1_AIR_AND_COMBUSTION: "c1-4",

  CHEMISTRY_S2_ATOMIC_STRUCTURE: "c2-1",
  CHEMISTRY_S2_PERIODIC_TABLE: "c2-2",
  CHEMISTRY_S2_CHEMICAL_REACTIONS: "c2-3",
  CHEMISTRY_S2_METALS_AND_REACTIVITY_SERIES: "c2-4",

  CHEMISTRY_S3_CHEMICAL_BONDING: "c3-1",
  CHEMISTRY_S3_MOLE_CONCEPT: "c3-2",
  CHEMISTRY_S3_ACIDS_BASES_AND_SALTS: "c3-3",
  CHEMISTRY_S3_ELECTROLYSIS: "c3-4",

  CHEMISTRY_S4_ORGANIC_CHEMISTRY: "c4-1",
  CHEMISTRY_S4_RATES_OF_REACTION: "c4-2",
  CHEMISTRY_S4_ENERGY_CHANGES_IN_REACTIONS: "c4-3",
  CHEMISTRY_S4_CHEMICAL_EQUILIBRIUM: "c4-4",

  // BIOLOGY
  BIOLOGY_S1_CELL_BIOLOGY: "b1-1",
  BIOLOGY_S1_CLASSIFICATION_OF_LIVING_THINGS: "b1-2",
  BIOLOGY_S1_NUTRITION_IN_PLANTS: "b1-3",
  BIOLOGY_S1_NUTRITION_IN_HUMANS: "b1-4",

  BIOLOGY_S2_HUMAN_BODY_SYSTEMS: "b2-1",
  BIOLOGY_S2_TRANSPORT_IN_PLANTS: "b2-2",
  BIOLOGY_S2_EXCRETION: "b2-3",
  BIOLOGY_S2_REPRODUCTION_IN_PLANTS: "b2-4",

  BIOLOGY_S3_ECOLOGY_AND_ENVIRONMENT: "b3-1",
  BIOLOGY_S3_COORDINATION_AND_RESPONSE: "b3-2",
  BIOLOGY_S3_REPRODUCTION_IN_HUMANS: "b3-3",
  BIOLOGY_S3_RESPIRATION: "b3-4",

  BIOLOGY_S4_GENETICS_AND_EVOLUTION: "b4-1",
  BIOLOGY_S4_BIOTECHNOLOGY: "b4-2",
  BIOLOGY_S4_DISEASE_AND_IMMUNITY: "b4-3",
  BIOLOGY_S4_HUMAN_INFLUENCE_ON_THE_ENVIRONMENT: "b4-4",
} as const;

export type TopicId = (typeof TOPIC_IDS)[keyof typeof TOPIC_IDS];
