export const CURRICULUM_DATA = {
  subjects: [
    "Physics (Advanced)",
    "Chemistry (Advanced)",
    "Biology (Advanced)",
    "Pure Mathematics (Advanced)",
    "Economics",
    "History (Advanced)",
    "Geography (Advanced)",
    "Subsidiary Mathematics",
    "Subsidiary ICT",
    "General Paper",
    "Literature in English (Advanced)",
    "Divinity",
    "Islamic Religious Education (Advanced)",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "English Language",
    "History & Political Education",
    "Geography",
    "Entrepreneurship Education",
    "Information & Communications Tech",
    "Kiswahili",
    "Luganda Language",
    "Literature in English",
    "Agriculture",
    "Fine Art",
    "Christian Religious Education",
    "Islamic Religious Education",
    "Commerce",
  ],
  curriculums: ["S1", "S2", "S3", "S4", "Advanced"],
  roles: ["student", "teacher", "parent", "administrator"],
};
